github actions 오류 수정3

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -19,13 +19,13 @@ jobs:
         run: |
           yarn ci
 
-      - name: Build
-        run: |
-          yarn build
+      # - name: Build
+      #   run: |
+      #     yarn build
 
-      - name: Run Lighthouse CI
-        # env:
-        #   LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
-        run: |
-          yarn install -g @lhci/cli
-          lhci autorun || echo "Fail to Run Lighthouse CI!"
+      # - name: Run Lighthouse CI
+      #   env:
+      #     LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
+      #   run: |
+      #     yarn install -g @lhci/cli
+      #     lhci autorun || echo "Fail to Run Lighthouse CI!"
